UPDATE BOOKS SET PRICE = 300 WHERE ID = (SELECT ID FROM BOOKS WHERE TITLE = 'Clean Code' AND PRICE = 0);
UPDATE BOOKS SET PRICE = 290 WHERE ID = (SELECT ID FROM BOOKS WHERE TITLE = 'Introduction to Algorithms' AND PRICE = 0);
UPDATE BOOKS SET PRICE = 485 WHERE ID = (SELECT ID FROM BOOKS WHERE TITLE = 'Structure and Interpretation of Computer Programs (SICP)' AND PRICE = 0);
UPDATE BOOKS SET PRICE = 790 WHERE ID = (SELECT ID FROM BOOKS WHERE TITLE = 'The Clean Coder' AND PRICE = 0);
UPDATE BOOKS SET PRICE = 180 WHERE ID = (SELECT ID FROM BOOKS WHERE TITLE = 'Code Complete' AND PRICE = 0);
UPDATE BOOKS SET PRICE = 350 WHERE ID = (SELECT ID FROM BOOKS WHERE TITLE = 'Design Patterns' AND PRICE = 0);
UPDATE BOOKS SET PRICE = 580 WHERE ID = (SELECT ID FROM BOOKS WHERE TITLE = 'The Pragmatic Programmer' AND PRICE = 0);